name: Update Time Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-time:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.MYTOKEN }}
        
    - name: Compile and run C++ program
      run: |
        # 编译程序
        g++ -o write_time write_time.cpp -std=c++11
        
        # 运行程序
        ./write_time
        
    - name: Configure Git user
      run: |
        git config --global user.name "MathsionYang"
        git config --global user.email "1114809057@qq.com"
        
    - name: Commit and push changes
      run: |
        git add timestamp.txt
        git diff --staged --quiet || git commit -m "Auto update: Add timestamp $(date +'%Y-%m-%d %H:%M:%S')"
        git push
